mySocialNetwork/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),


]

mySocialNetwork/posts/urls.py
# POSTS URLS.PY

from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),


]

mySocialNetwork/simplesocial_project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),

    # URL for accounts application
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

    # 
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),

    # URL for groups application
    path('groups/', include('groups.urls', namespace='groups')),
    # URL for groups application
    path('posts/', include('posts.urls', namespace='posts')),

]

mySocialNetwork/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Infinitive Network</title>

    <!-- BOOTSTRAP -->

    <!-- BOOTSTRAP 3 -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet"> 

    <!-- CUSTOM CSS FILES -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

</head>
<body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-inverse mynav" role="navigation" id="navbar">
        <div class="container">
            <li> <a class="navbar-brand mynav" href="{% url 'home' %}">Infinitive Network</a> </li>
            <ul class="nav navbar-nav navbar-right">
                
                {% if user.is_authenticated %}
                    <li> <a href="{% url 'posts:create' %}">Post</a> </li>
                    <li> <a href="{% url 'groups:all' %}">Groups</a> </li>
                    <li> <a href="{% url 'groups:create' %}">Create Group</a> </li>
                    <li> <a href="{% url 'accounts:logout' %}">Logout</a> </li>
                {% else %}
                    <li> <a href="{% url 'groups:all' %}">Groups</a> </li>
                    <li> <a href="{% url 'accounts:login' %}">Login</a> </li>
                    <li> <a href="{% url 'accounts:signup' %}">Sign Up</a> </li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container mycontent">

        {% block content %}
        
        {% endblock content %}
    </div>

</body>
</html>

mySocialNetwork/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>Welcome to Infinitive Network</h1>
    </div>

{% endblock content %}

mySocialNetwork/templates/test.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>You are now logged in</h1>
    </div>

{% endblock content %}

mySocialNetwork/templates/thanks.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>Thank for visiting, come back soon.</h1>
    </div>

{% endblock content %}